#ifndef CONFIG_H
#define CONFIG_H

#define OLED_WIDTH 128
#define OLED_HEIGHT 32
#define OLED_LINES 4
#define OLED_MAXLEN 21

#define DISPLAY_LINES OLED_LINES-2
#define DISPLAY_SCROLL_DELAY 250

#define BUTTON_DEBOUNCE_DELAY 50

#define BATTERY_READ_DELAY 1000
#define BATTERY_COEFFICIENT 0.00582

#define SLEEP_AUTOSLEEP_SECONDS 60

#endif
